base_path: "compose-multiplatform"
preserve_hierarchy: false
commit_message: "Update translations (%language%)"
pull_request_title: "Update Translations [skip ci]"

files:
  - source: "/**/composeResources/values/strings.xml"
    translation: "/%original_path%-%android_code%/%original_file_name%"
  - source: "/**/res/values/strings.xml"
    translation: "/%original_path%-%android_code%/%original_file_name%"
