#!/usr/bin/env bash

echo ""
echo "1/1 Running detekt..."
OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detekt > "$OUTPUT" 2>&1
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  cat "$OUTPUT"
  rm "$OUTPUT"
  echo ""
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm "$OUTPUT"
